In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/AP-State-Skill-Development-Corporation/Datasets/master/Classification/diabetes.csv')

In [3]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [4]:
df.shape

(768, 9)

In [5]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [6]:
from sklearn.preprocessing import LabelEncoder

In [7]:
lbc = LabelEncoder()

In [9]:
x=df.drop('Outcome',axis='columns')

In [10]:
y=df['Outcome']

In [11]:
x.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  
0                     0.627   50  
1                     0.351   31  
2                     0.672   32  
3                     0.167   21  
4                     2.288   33

In [12]:
y.head()

0    1
1    0
2    1
3    0
4    1
Name: Outcome, dtype: int64

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
xtr,xtt,ytr,ytt = train_test_split(x,y,test_size=0.30,random_state=42)

In [15]:
from sklearn.neighbors import KNeighborsClassifier

In [44]:
model = KNeighborsClassifier(n_neighbors=49)

In [45]:
model.fit(xtr,ytr)

KNeighborsClassifier(n_neighbors=49)

In [53]:
ytr[:3]

334    0
139    0
485    1
Name: Outcome, dtype: int64

In [47]:
xtr[:1].values

array([[ 1.  , 95.  , 60.  , 18.  , 58.  , 23.9 ,  0.26, 22.  ]])

In [54]:
model.predict(xtr[:3])

array([0, 0, 0], dtype=int64)

In [25]:
pred = model.predict(xtt)

In [26]:
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score

In [27]:
confusion_matrix(ytt,pred)

array([[108,  43],
       [ 32,  48]], dtype=int64)

In [28]:
accuracy_score(ytt,pred)

0.6753246753246753

In [29]:
precision_score(ytt,pred)

0.5274725274725275

In [42]:
acc=[]
for i in range(49,53,2):
    model = KNeighborsClassifier(n_neighbors=i)
    model.fit(xtr,ytr)
    pred = model.predict(xtt)
    from sklearn.metrics import confusion_matrix,accuracy_score,precision_score
    print(confusion_matrix(ytt,pred))
    acc.append(accuracy_score(ytt,pred))
    precision_score(ytt,pred)

[[135  16]
 [ 41  39]]
[[134  17]
 [ 43  37]]


In [43]:
acc

[0.7532467532467533, 0.7402597402597403]