# Classification_Supervised_MachineLearning
#### DataSet :- Homebuyer.csv

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv('https://raw.githubusercontent.com/AP-State-Skill-Development-Corporation/Datasets/master/Classification/HomeBuyer.csv')

In [4]:
df.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [6]:
df.isnull().sum()

Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [7]:
df.shape

(400, 3)

In [9]:
from sklearn.preprocessing import LabelEncoder

In [10]:
lbc = LabelEncoder()

In [11]:
x=df.drop('Purchased',axis='columns')

In [12]:
y=df['Purchased']

In [14]:
x.head()

Age  EstimatedSalary
0   19            19000
1   35            20000
2   26            43000
3   27            57000
4   19            76000

In [15]:
y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
xtr,xtt,ytr,ytt=train_test_split(x,y,test_size=0.30,random_state=42)

In [18]:
from sklearn.neighbors import KNeighborsClassifier

In [37]:
model = KNeighborsClassifier(n_neighbors=5)

In [38]:
model.fit(xtr,ytr)

KNeighborsClassifier()

In [42]:
ytr[:5]

157    0
109    0
17     1
347    1
24     1
Name: Purchased, dtype: int64

In [43]:
model.predict(xtr[:5])

array([0, 0, 0, 1, 1], dtype=int64)

In [41]:
pred = model.predict(xtt)

In [27]:
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score

In [28]:
confusion_matrix(ytt,pred)

array([[65,  8],
       [17, 30]], dtype=int64)

In [29]:
accuracy_score(ytt,pred)

0.7916666666666666

In [30]:
precision_score(ytt,pred)

0.7894736842105263

In [35]:
acc=[]
for i in range(3,75,2):
    model=KNeighborsClassifier(n_neighbors=i)
    model.fit(xtr,ytr)
    pred = model.predict(xtt)
    from sklearn.metrics import confusion_matrix,accuracy_score,precision_score
    print(confusion_matrix(ytt,pred))
    acc.append(accuracy_score(ytt,pred))
    precision_score(ytt,pred)

[[65  8]
 [17 30]]
[[69  4]
 [18 29]]
[[69  4]
 [21 26]]
[[70  3]
 [21 26]]
[[68  5]
 [21 26]]
[[69  4]
 [23 24]]
[[70  3]
 [26 21]]
[[70  3]
 [26 21]]
[[70  3]
 [26 21]]
[[70  3]
 [27 20]]
[[70  3]
 [25 22]]
[[70  3]
 [26 21]]
[[70  3]
 [25 22]]
[[70  3]
 [27 20]]
[[70  3]
 [27 20]]
[[70  3]
 [27 20]]
[[70  3]
 [27 20]]
[[70  3]
 [27 20]]
[[70  3]
 [27 20]]
[[70  3]
 [27 20]]
[[70  3]
 [27 20]]
[[70  3]
 [27 20]]
[[70  3]
 [27 20]]
[[70  3]
 [28 19]]
[[70  3]
 [28 19]]
[[70  3]
 [28 19]]
[[70  3]
 [28 19]]
[[70  3]
 [28 19]]
[[70  3]
 [28 19]]
[[70  3]
 [28 19]]
[[70  3]
 [28 19]]
[[70  3]
 [28 19]]
[[70  3]
 [28 19]]
[[70  3]
 [29 18]]
[[70  3]
 [29 18]]
[[70  3]
 [29 18]]


In [36]:
acc

[0.7916666666666666,
 0.8166666666666667,
 0.7916666666666666,
 0.8,
 0.7833333333333333,
 0.775,
 0.7583333333333333,
 0.7583333333333333,
 0.7583333333333333,
 0.75,
 0.7666666666666667,
 0.7583333333333333,
 0.7666666666666667,
 0.75,
 0.75,
 0.75,
 0.75,
 0.75,
 0.75,
 0.75,
 0.75,
 0.75,
 0.75,
 0.7416666666666667,
 0.7416666666666667,
 0.7416666666666667,
 0.7416666666666667,
 0.7416666666666667,
 0.7416666666666667,
 0.7416666666666667,
 0.7416666666666667,
 0.7416666666666667,
 0.7416666666666667,
 0.7333333333333333,
 0.7333333333333333,
 0.7333333333333333]