# Naive Bayes Algorithm

In [27]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [28]:
dfmale = pd.read_csv('Indian-Male-Names.csv')
dffemale = pd.read_csv('Indian-Female-Names.csv')

In [29]:
dfmale.head()

name gender    race
0          barjraj      m  indian
1     ramdin verma      m  indian
2  sharat chandran      m  indian
3  birender mandal      m  indian
4             amit      m  indian

In [30]:
dffemale.head()

name gender    race
0          shivani      f  indian
1             isha      f  indian
2  smt shyani devi      f  indian
3            divya      f  indian
4            mansi      f  indian

In [36]:
dfmale=dfmale.drop('race',axis=1)

In [37]:
dfmale.head()

name  gender
0          barjraj       1
1     ramdin verma       1
2  sharat chandran       1
3  birender mandal       1
4             amit       1

In [38]:
dffemale=dffemale.drop('race',axis=1)

In [39]:
dffemale.head()

name  gender
0          shivani       0
1             isha       0
2  smt shyani devi       0
3            divya       0
4            mansi       0

In [40]:
df = pd.concat([dfmale,dffemale])

In [48]:
dffinal=df.sample(frac=1)

In [50]:
dffinal.head()

name  gender
6873       deepa       0
15080     kavita       0
2498   smt nisha       0
278     priyansi       0
891     chanchal       0

In [44]:
from sklearn.model_selection import train_test_split 

In [46]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction import DictVectorizer

In [51]:
names = dffinal['name']
cv=CountVectorizer()

In [55]:
x=cv.fit_transform(names.values.astype('U'))

In [56]:
y=dffinal.gender

In [57]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.33,random_state=42)

In [58]:
from sklearn.naive_bayes import MultinomialNB

In [59]:
model = MultinomialNB()

In [60]:
model.fit(x_train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [61]:
model.score(x_test,y_test)

0.9128822055137844

In [63]:
sample1 = ['vinod']
vector1=cv.transform(sample1).toarray()
model.predict(vector1)

array([1], dtype=int64)

In [64]:
sample1 = ['roja']
vector1=cv.transform(sample1).toarray()
model.predict(vector1)

array([0], dtype=int64)

In [65]:
sample1 = ['radha']
vector1=cv.transform(sample1).toarray()
model.predict(vector1)

array([0], dtype=int64)

In [66]:
sample1 = ['kumar']
vector1=cv.transform(sample1).toarray()
model.predict(vector1)

array([1], dtype=int64)